### ISSUE TITLE
CSS Class.docutils does not render like tables

### ISSUE THREAD

**Issue by markussoeth** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#103]
I realized that the style for defenitionlists with the class .docutils do not render like "tables" (div class t3-row) for "propertys", "Data type" and "examples".
So please add this CSS to the "theme.css"

dl.docutils{
    background-color: #f2ebe3;
    border: 1px none #888;
    border-top: 2px solid #988d81;
    clear: both;
    margin-bottom: 30px;
    margin-top: 30px;
    position:relative;
}
dl.docutils dt{
    padding: 12px 8px; 
    color: #b34700;
    font-size: 9px;
    font-weight: 400;
}
dl.docutils dd{
    padding: 12px 8px;
    margin:0;
}

dl.docutils dt:nth-of-type(1){    
    font-weight: 700;
    margin-right: 8px;
    min-width: 30%;
    margin: 0;
    position:absolute;
}

dl.docutils dd:nth-of-type(1){    
    font-weight:700;
    position:absolute;
    margin-top:20px;
}

dl.docutils dt:nth-of-type(2){    
    border-left: 4px solid #fff;
    position:relative;
    left:30%;
    top:0;
}
dl.docutils dd:nth-of-type(2){    
   border-left: 4px solid #fff;
    position:relative;
    left:30%;
    top:0;
    max-width:70%;
}
dl.docutils dt:nth-of-type(3){    
    border-top: 4px solid #fff;
}

**Comment by sypets** [comment]
Is this still a problem? Can you add a link to a page that is not rendered correctly?

For general rendering problems, please add issues to the [t3docSphinxThemeRtd repo](
https://github.com/TYPO3-Documentation/t3SphinxThemeRtd)

I am closing this now. I believe there was a problem with rendering definitions lists, which is now resolved.
