### ISSUE TITLE
Localization $arguments

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#114]
The description about $arguments on https://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html#localization
is not very clear. Example would be nice.

**Comment by DavidBruchmann** [comment]
Especially the wildcard-option needs an example or more explanation.

**Comment by Kalabybis** [comment]
Yes, true. It refers to the PHP function vsprintf. Look here http://php.net/manual/de/function.vsprintf.php 

A good example from the comments.:
<?php 
$string = <<<THESTRING 
I like the state of %1\$s <br /> 
I picked: %2\$d as a number, <br /> 
I also picked %2\$d as a number again <br /> 
%3\$s<br /> 
THESTRING; 

$returnText = vprintf(  $string, array('Oregon','7','I Love Oregon')  ); 

echo $returnText;

**Comment by janmaennig** [comment]
https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/310

**Comment by linawolf** [comment]
merged
