### ISSUE TITLE
Menu "Changelog 8-dev" Error 404 Not Found

### ISSUE THREAD

**Issue by M-arcus** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#120]
When clicking on the link in the sidebar ([_Changelog 8-dev ➜_](https://docs.typo3.org/typo3cms/extensions/core/latest/)), a 404 Error occurs.

![404doc](https://cloud.githubusercontent.com/assets/25648755/25520153/2f35e80c-2bfb-11e7-87ec-090bd7a5716c.png)

Correct would be:
 - https://docs.typo3.org/typo3cms/extensions/core/ 
 - https://docs.typo3.org/typo3cms/extensions/core/8-dev/

**Comment by M-arcus** [comment]
Additionally on _https://docs.typo3.org/typo3cms/References/Index.html_:

![404doc2](https://cloud.githubusercontent.com/assets/25648755/25520350/e9135692-2bfb-11e7-9639-a90e2a2d0616.png)

**Comment by M-arcus** [comment]
Wrong repo, sorry

**Comment by 60FLORIBERT** [comment]
Can you support us for to improve our agriculture for to stop ✋ hunger, poverty and drought. Restore hope.please. See Floribert Kiebo on LinkedIn, Facebook, Google +or @KieboMwan. Thank and God will bless you.

**Comment by 60FLORIBERT** [comment]
Hunger is a big problem. With the will we can win it
