### ISSUE TITLE
Readme instructions outdated

### ISSUE THREAD

**Issue by adimit** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#133]
```
Error: Config directory doesn't contain a conf.py file.
```

When running `make html`, (as instructed by the readme) `shpinx-build` will emit the above error and refuse to build the documentation.

It seems that the project is meant to be viewed through the Typo3 `sphinx`-extension, which may obviate the need for a `conf.py` (I have no experience with neither `sphinx` nor the Typo3 extension.)

Additionally, after I generated a basic `conf.py`, the `contents.rst` file is missing when building from command line. I'm assuming `Index.rst` is supposed to fulfill that role.

I can provide a PR that will add a `contens.rst` & `conf.py`, however, I haven't gotten the sidebar to properly render (i.e. show the full navigation) in local builds. Alternatively, the Readme could be update to indicate that the documentation is meant to be viewed or compiled using the TER extension.

**Comment by marble** [comment]
@adimit Hi Aleksandar, thanks for pointing me to this project. The readme and the make files here are a leftover and should be removed. I just did that. And I fixed some more reST errors. What system are you on? You now can do a perfect local rendering with this Docker container: https://github.com/t3docs/docker-render-documentation Please check that readme file. If you are on Windows: Please help writing the README for Windows users.

**Comment by adimit** [comment]
Sorry, I'm on Linux, so no Windows documentation forthcoming from me. Thanks for the pointer, I'll try it out. I'll send you some fixes in the meantime…

**Comment by marble** [comment]
On Linux? You'll have fun with it, it think.
