### ISSUE TITLE
Blog example is obsolete

### ISSUE THREAD

**Issue by vojtasvoboda** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#158]
Hi, I'm trying to onboard in TYPO3 as fast as possible, so I've started with: [Blog example extension](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/3-BlogExample/Index.html). But immediately after installation, I'm getting: `Class 'Tx_Extbase_Utility_Extension' not found` exception.

Now [I found](https://extensions.typo3.org/extension/blog_example/), that Blog example is an Outdated extension with the last update at 2011!

Could you please update documentation, or send me a link for different example to smooth onboarding?

**Comment by marble** [comment]
Yes, unfortunately extbase and fluid manuals are in a bad shape. Pick the example code from the Extbase book. See: https://docs.typo3.org/typo3cms/TellMeSomethingAbout/Topics/Extbase.html

**Comment by vojtasvoboda** [comment]
@marble I'm sorry, but on that link is nothing I could use - just two links in German language, one book on LeanPub which is paid and one outdated link to Blog example extension I've mentioned previously 😢 

There is really no step-by-step basic tutorial helps me with onboarding?

**Comment by marble** [comment]
@vojtasvoboda nothing? The line pointing to the extbase book also has this link: https://github.com/plobacher/extbasebookexample That version is NOT outdated as you complained above. I can recommend that book. Together with the code it has exactly the instructions you're asking for. And, yes, it is a book: That shows there is quite a bit to learn and to know. A short step by step single page just doesn't work, I think. Ålso: You may want to get yourself an invite to https://typo3.slack from https://forger.typo3.com/slack That is the place where the community meets and things can be asked and discussed. I suggest to go over there as discussing things here is pretty inefficient.

**Comment by vojtasvoboda** [comment]
@marble Thanks a lot, I'm now at Slack. I found the ExtBase book, but it's paid. I'm now looking for free resources because I just want to decide if TYPO3 is the great candidate for my next project or not.
