### ISSUE TITLE
In section: Developing a custom viewhelper add information about $escapeOutput

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#173]
Between TYPO3 7 and 8 the default behaviour of ViewHelpers was changed:

before: HTML code was output as is
after: HTML output is escaped: `<` becomes `&lt;`

The default behaviour can be changed:

```
/**
     * By default the output is escaped.
     *
     * @var bool
     */
    protected $escapeOutput = false;
```
In Fluid  f:format.htmlentities, f:format.stripTags etc. can be applied.

see : https://typo3.slack.com/archives/C025BQLFA/p1499087019054498

**Comment by DanielSiepmann** [comment]
@lolli42 or @mbrodala might you correct or confirm my last comment? I'll update the docs accordingly afterwards.

**Comment by mbrodala** [comment]
Yes, escaping always existed but before TYPO3v8 there was a single property `$escapingInterceptorEnabled` which was used to control the whole escaping behavior.

Since TYPO3v8 and standalone Fluid we have `$escapeOutput` and `$escapeChildren` instead.
