### ISSUE TITLE
Improve language: grammar / style / vocabulary

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#184]
Using wrong grammar / phrases / vocabulary:

* [x] "Now you have a good **_oversight_** how you can use Extbase also for development of backend modules" (https://docs.typo3.org/typo3cms/ExtbaseFluidBook/10-Outlook/2-Backend-modules.html)
  * better: "Now you know how you can use Extbase for the development of backend modules." or
  * or: "Now you have gained some understanding of how you can use Extbase to develop backend modules."

No specific error, but could generally be improved. 

* [x]  Entire page BE modules: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/10-Outlook/2-Backend-modules.html

**Comment by sypets** [comment]
Tools you can use to double-check the language:

dictionary / lookup words:
* dictionary: https://www.m-w.com (Merriam Webster)

tools 
* Grammarly Browser plugin: https://www.grammarly.com/

forums
* English StackExchange: https://english.stackexchange.com/
* English language learners StackExchange: https://ell.stackexchange.com/

**Comment by alexanderschnitzler** [comment]
I fixed quite a lot of typos with 41a9dea and I replaced a lot of german terms with english ones in ac89460.

**Comment by sypets** [comment]
@alexanderschnitzler Awesome! Feel free to close this issue.

**Comment by alexanderschnitzler** [comment]
I don't. I just worked on the tip of the iceberg. There are still so many sentences that nobody understands. ^^

**Comment by mbrodala** [comment]
@alexanderschnitzler Thanks a lot for getting started with this. Just one suggestion: please always make a PR so others can have a look. :-)

**Comment by sypets** [comment]
@mbrodala @alexanderschnitzler Yes, good point: About PR, merging, etc. we usually do it this way:

* even if you have write access to git repository, please create PR. 
* in core contribution, you must create issue, for docs you do not (sometimes makes sense, though)
* but, as in core contribution change should not include several unrelated changes but focus on one thing (like you did for the spelling)
* wait for others to review or merge. If it's urgent or takes too long, ping someone (e.g. on Slack)
* you can add additional commits to your PR
* we usually don't merge our own PRs.
* start with small changes, wait for feedback (people do still make mistakes with reST formatting or are unclear about some guidelines, so it's usually not a good idea to start a huge change where you may have to correct several things)

There are some exceptions to this though:

* for minor nobrainer changes, we sometimes commit directly, especially on texts where we correct stuff we originally wrote ourselves. 
* some people do commit things directly, but then they are already the maintainer for a manual like Lolli for "TYPO3 Explained". Until we do find a maintainer for the Extbase Book, I think we should stick to standard procedure.

**Comment by lolli42** [comment]
In this case I actually would give Alexander free hands on this repository: He is a very long time contributor and knows extbase better than most others. His pushes to the repo until now have all been good and it will be an additional burden for him if he starts rewriting bigger stuff to work with PR's all the time. As far as I understood, he is planning some bigger modernizations. This means he is the first one doing this for years, so we should do as much as possible to support Alexander. I guess he will fork away one base version soon to start on the bigger stuff as part of extbase docs for decent core versions. This will also make it rather easily possible to look up old stuff if really needed.

**Comment by mbrodala** [comment]
Fine with me but I cannot promise that I'll be able to keep track of the changes thus I cannot do any suggestions about structure and content/wording.

If feedback is desired, just post a PR, otherwise go ahead and tame this beast.

**Comment by alexanderschnitzler** [comment]
My first tasks are about technical changes anyway. I am not a native english speaker, so I will not go on and rewrite sentences because I think I know a better wording/grammar.

My goal is to have correct information at first. If I am unsure about things, I will create PR‘s and consult others. Just like yesterday when I pinged dozens of people about the __hmac stuff in the property mapper.

Also I will not push structural changes to master. That‘s something I would prepare and suggest before releasing that to the world.
