### ISSUE TITLE
Change old and obsolete @dontvalidate to @ignorevalidation.

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#186]
https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/185

Change old and obsolete @dontvalidate to @ignorevalidation.
Need to be adjusted in versions from 6.2 on.

**Comment by alexanderschnitzler** [comment]
Has been resolved with #b3f823b
