### ISSUE TITLE
Clarify Fluid Inline Notation

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#219]
see https://docs.typo3.org/typo3cms/ExtbaseFluidBook/8-Fluid/1-basic-concepts.html#inline-notification-for-view-helpers

* should be "inline notation", not "Inline Notification"?
* this chapter is hidden, perhaps move it up in toc hierarchy
* possibly, add reference to http://www.fluid-converter.com/

**Comment by linawolf** [comment]
There is a separate section by now. Just added the reference to the fluid converter
