### ISSUE TITLE
Structure: Plan for this manual?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#226]
This manual has several problems:

* Several things are general, such as "Developing Custom ViewHelpers" and not specific to the goal described here (Developing Extensions - primarily plugins - with Extbase / Fluid)
* Too lengthy for online reading and maintainance, some things are described several times, several example extensions which are not being updated

## Proposal

This is also inspired by #198 and what others have suggested. 

* Create a tutorial: "Developing plugins with Extbase & Fluid" covering only that. This could be a separate manual or could exist in "Content & plugins" section in "TYPO3 Explained"
* Create an "Extension Development Getting Started", either [within TYPO3 EXplained](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/CreateNewExtension/Index.html) or as separate manual
* As is currently being done for Fluid, create a startpage for "Extbase" in TYPO3 Explained which gives an introduction and gives overview to existing documentation
* Move some general things to "TYPO3 Explained", e.g. "Creating Custom ViewHelpers" to "Fluid" page that is currently being developed.
* Take down the book and link to appropriate start page, e.g. "Extbase" in "TYPO3 Explained as described above. 
* Section "Extbase" in "TYPO3 Explained" could contain a start page, introduction and a reference
* For  9.5 we could refer to the book by Michael Schams

## Some things have already been moved from the book

* Backend Modules is already covered in [TYPO3 Explained](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/BackendModules/BackendModuleApi/Index.html)
* Command Controllers is already covered in [TYPO3 Explained](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/BackendModules/CliScripts/Index.html), see also these PR, that already perform the move: #260, https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/468

## Related:

* Split Fluid out of the book: #198
* https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Extbase/issues/143
* [Slack](https://typo3.slack.com/archives/C028JEPJL/p1547724770173700)

**Comment by sypets** [comment]
I edited the description to create a "proposal" and closed some of my issues which are no longer relevant.

**Comment by linawolf** [comment]
This Book will be discontinued. Outdated content will be removed and valid content moved and shortened
