### ISSUE TITLE
Developing a custom ViewHelper: error in examples

### ISSUE THREAD

**Issue by clivebeckett** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#229]
I guess there is an error in some of the examples on [Developing a Custom ViewHelper](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/8-Fluid/8-developing-a-custom-viewhelper.html):

As mentioned in the text below the example for **The implementation** it should be
```
use \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
```
instead of
```
use TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper;
```

This appears in several examples on the page but will lead to a deprecated note marked as strong.

**Comment by mbrodala** [comment]
That's absolutely correct and recommended since TYPO3v8. Can you make a PR for this? Just hit the _Edit me on Github_ button in the upper right to fix this. :-)

**Comment by clivebeckett** [comment]
> Can you make a PR for this?

Never done that before but I’ll try :)
