### ISSUE TITLE
Layout with sidebar is broken

### ISSUE THREAD

**Issue by GhostGambler** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#244]
Using a sidebar near the end of the page breaks the layout, see for example the following two sites:

https://docs.typo3.org/typo3cms/ExtbaseFluidBook/3-BlogExample/5-Get-Blog-from-the-Repository.html

https://docs.typo3.org/typo3cms/ExtbaseFluidBook/3-BlogExample/12-automatic-persistence-of-the-domain-logic.html

and a screenshot showing the problem:

<img width="1396" alt="Bildschirmfoto 2019-03-20 um 15 40 25" src="https://user-images.githubusercontent.com/969344/54693301-a45e6180-4b26-11e9-8894-5dadd3f3290a.png">

**Comment by sypets** [comment]
Thank you for your report. I have seen this as well. In general, using sidebars one has to be careful. For now, I would recommend not to do that.

I will have also opened an issue in the [theme repo](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd): https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/109
