### ISSUE TITLE
Fluid: Move things from the Wiki

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#278]
Move (and update / delete) content from Wiki: 

* [ ] https://wiki.typo3.org/Fluid
* [ ] https://wiki.typo3.org/Fluid_Inline_Notation
* [ ] https://wiki.typo3.org/FluidSyntax

When moving please make sure to always:
* add a link to new content
* always add the category Moved: `[[category: Moved]]`

see: https://wiki.typo3.org/WikiMigration

**Comment by susannemoog** [comment]
Moved by Lina as part of https://github.com/TYPO3-Documentation/T3DocTeam/issues/154 - closing this one here.
