### ISSUE TITLE
Make text more concise / shorten

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#287]
Some of the text can be shortened to about half of the length without loosing much of the information.

While we do think having a few introductory sentences is good and this text does a good job of taking the user by the hand and leading him through the material, a few suggestions:

* remove historical references to TYPO3 4, pibase programming, flow, history of Neos etc. that are no longer of much value today. The reader wants to learn extension development. 
* remove redundancies: Some pages contain redundancies where one thing is mentioned several times in different words. Make text as short as possible without loosing information or writing style (friendly!)

**Comment by linawolf** [comment]
We are at it ;)
