### ISSUE TITLE
Provide updated example extension and reduce number of example extensions to one which is actively maintained.

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#288]
This book refers to several extensions, all of which are not available for TYPO3 9 and above:

* blog example in https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/3-BlogExample/Index.html
* [store_inventory](https://github.com/TYPO3-Documentation-Examples/store_inventory) in [Creating a first extension](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/4-FirstExtension/Index.html)
* [sjr_offers](https://extensions.typo3.org/extension/sjr_offers/) is mentioned in [Modeling the Domain](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/5-Domain/Index.html) - available only for 6.2

**I would propose to stick to one sample extension if possible and keep this one updated!** However, I have not checked sufficiently if this is possible with the current text. A journey through the blog example is based heavily on the blog example. Having up to date code that works would be very helpful.

Necessary steps: 

* [ ] Decide on best approach: update existing extensions, create new one(s)?
* [ ] Provide updated sample extension(s)
* [ ]  Find appropriate place to put example extensions where they can be easily maintained. Currently there is https://github.com/TYPO3-extensions/examples which is a mirror of git.typo3.org

**Comment by linawolf** [comment]
The extension "examples" is not an example Extension for Extbase / Fluid. It is an extension that contains examples from TYPO3 Explained, how to configure Backend stuff, how to write to the log etc. It can be used to provide Screenshots.

So I would opt for updating the extensions Blog Example. What we are doing with store inventory could be easily demonstrated on the Blog Example as well

I would opt for moving it to in https://github.com/TYPO3-Documentation/Blog-Example

**Comment by franzholz** [comment]
Yes please do not wait any longer and start with it now!
Please make a new Github repository, owned by the documentation team, available for pull requests!

**Comment by linawolf** [comment]
Work in progress
