### ISSUE TITLE
Streamline custom validator examples

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#315]
Raised by @maikusch, the sections within `Documentation/9-CrosscuttingConcerns/2-validating-domain-objects.rst` are misleading. Code examples were adjusted via https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/commit/d9509fc8945e54679423b378ff3493492fab0fc4#diff-eaedc983c891f372262095aee2860fc6 but do no longer match. `validate()` is now implemented instead of `isValid()`, but this does not match to extending the `AbstractValidator` class.

Which way is preferred and why. This way should be used through the whole section, with a small side note why it is preferred over the other.

**Comment by linawolf** [comment]
Done and moved to typo3 explained
