### ISSUE TITLE
The ViewHelper Section misses Information on the WidgetViewHelper

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#331]
There should be information of how to write a WidgetViewHelper as is tried here for example:
https://stackoverflow.com/questions/50740942/typo3-custom-widget-viewhelper

**Comment by alexanderschnitzler** [comment]
As widgets are dead as of version 11.0, they don't need to be documented any more.
Feel free to reopen if you disagree.

**Comment by linawolf** [comment]
Dead...? Is there something better by now?

**Comment by alexanderschnitzler** [comment]
Not in terms of a view helper. widgets contained too much logic because they initiated a sub request. People should stick with view helpers for simple things and use the controller for advanced logic like pagination.
