### ISSUE TITLE
Example is broken: following the instructions results in Error 500

### ISSUE THREAD

**Issue by legomaennchen** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#345]
I followed the instructions 1 by 1 and copy/paste the examples to the files they should be in. The part with database is working fine - but the plugin cannot be finished, for all I got is an error 500 without a proper error log in the database. I checked all twice for error in structure, but it is exactly like the described one.

**Comment by fawmi** [comment]
@legomaennchen  can you explain, which example do you mean? 
A link to the page or the section title would help either.

**Comment by linawolf** [comment]
The examples in this book are severely outdated. We are therefore in the process of replacing this book. stay tuned.
