### ISSUE TITLE
Class mapping example of Modelling the Class Hierarchy should be PHP instead of TypoScript

### ISSUE THREAD

**Issue by the-coding-owl** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#357]
The example shows the old way of doing the class mapping in TypoScript, but this is not up2date for TYPO3 10 anymore.
I would change the example to PHP, but I do not know how this should be translated exactly. Actually I wanted to take a look on how it should be done and stumbled across this issue.

**Comment by SZChimp** [comment]
Hi, i already opened a PR for this exact issue: https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/454

**Comment by linawolf** [comment]
done
