### ISSUE TITLE
"Modeling the Class Hierarchy": TypoScript configuration not possible with TYPO3 v10

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#408]
The page https://docs.typo3.org/m/typo3/book-extbasefluid/10.4/en-us/6-Persistence/5-modeling-the-class-hierarchy.html shows typoscript to configure table names via `config.tx_extbase.persistence.classes`.

This is not possible anymore in TYPO3 v10, see https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

**Comment by helsner** [comment]
Lol, i just noticed that too.
The Docu is up-to-date on master though - https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/6-Persistence/5-modeling-the-class-hierarchy.html

So i don't know how that is handled, but the basic docs are existent, just missing in the v10 version

**Comment by helsner** [comment]
What could also be noted is the following example:

```
MyVendor\MyExtension\Domain\Model\Organization {
   mapping {
      tableName = tx_myextension_domain_model_party
      columns {
         title.mapOnProperty = title
      }
   }
}
```

```
\MyVendor\MyExtension\Domain\Model\Organization::class => [
    'tableName' => 'tx_myextension_domain_model_party',
    'properties' => [
        'title' => [
            'fieldName' => 'title'
        ],
    ],
];
```

**Comment by helsner** [comment]
@linawolf hi - i guess this could be closed now after you applied my patch?
