### ISSUE TITLE
Status on view.pluginNamespace

### ISSUE THREAD

**Issue by remonator** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#431]
The doc mentions:

https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/blob/c611b1d52118cb98ada6ec0a9cc99b4d58c34aa9/Documentation/b-ExtbaseReference/Index.rst#L304

What's the status of this?

**Comment by mbrodala** [comment]
The `pluginNamespace` option still exists in the code and was not deprecated. So for now you can continue to use it.
