### ISSUE TITLE
Incorrect relation between persistence manager and repositories

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#436]
From https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/blob/380aa6f/Documentation/3-BlogExample/10-Returning-the-result-to-TYPO3.rst:

> The persistence manager will walk through all used repositories and collect the new and the deleted objects. In our case, the persistence manager asks the blog repository about such objects.

Technically this is incorrect. The PM does not use repositories at all and the Extbase persistence can be used without repositories just fine. Repositories are merely a facade on top of the PM and querying.

**Comment by linawolf** [comment]
Yes the whole section was very messy. Removed it in my quest to replace this book
