### ISSUE TITLE
Crossreference labels without linktext

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#44]
Some labels are defined at places where they are NOT in front of a headline. So they don't have an automatic link text and are difficult to use. This can be made better!

To find them, see:https://docs.typo3.org/typo3cms/ExtbaseFluidBook/Targets.html and watch out for '...' instead of a linktext:

![029](https://cloud.githubusercontent.com/assets/307057/10904776/07a15a50-8216-11e5-8cb4-867f8388ca8e.png)

**Comment by Chrissitopher** [comment]
See https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/commit/80ef8cd1af981c9376b85066b0c8e405dd7cd962
