### ISSUE TITLE
No vendor needed - Configuring the plugin

### ISSUE THREAD

**Issue by ayacoo** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#463]
According to https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.1/Deprecation-88995-CallingRegisterPluginWithVendorName.html the following page should be up2date:  https://docs.typo3.org/m/typo3/book-extbasefluid/10.4/en-us/4-FirstExtension/7-configuring-the-plugin.html

**Comment by linawolf** [comment]
The content is severely outdated all together and will removed
