### ISSUE TITLE
Enrich forward() segment in Dispatching Docs

### ISSUE THREAD

**Issue by helsner** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#464]
https://docs.typo3.org/m/typo3/book-extbasefluid/10.4/en-us/10-Outlook/6-dispatching.html#forwarding-a-request

I don't really know how to express the issue, but it is already reported as forge issue here:
https://forge.typo3.org/issues/91671

Currently it seems that the forwarding is broken, at least it did not work as expected while the code block in the forge issue provides a solution, at least in my case, forwarding across different extensions.
I would provide a small textblock to describe this, but i don't understand the code good enough to verify if it is correct, that the docs should be extended or the code is an actual bug.
Could someone help us out on this one and give some hints? As mentioned i would extend the docs as far is i can if it is indeed a docs "issue"

Note:
This should only be for the v10 version as there is a new ForwardResponse in v11 which is already documented (nice!!)

**Comment by mbrodala** [comment]
IMO it sounds like a bug which should then be fixed.

(Notice that, `->forward()` is [already deprecated in TYPO3v11](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92815-ActionControllerForward.html) and [replaced by the new `ForwardResponse`](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Feature-92815-IntroduceForwardResponseForExtbase.html).)

**Comment by helsner** [comment]
Would it be valid to note the Bug in the docs?
As there is already a replacement i would expect this bug to be "not that important" , which could lead to no patch.
So the addition in the doc might be helpful for those that keep v10 and still develop further

**Comment by mbrodala** [comment]
TBH it doesn't feel right to provide an evident workaround as official documentation. We should strife for fixing the issue in TYPO3 instead.
