### ISSUE TITLE
Missing mention of header/footer assets

### ISSUE THREAD

**Issue by helsner** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#470]
Hi -
i'm kinda missing the header/footer assets in the docs.
Those sections can be added into the fluid template and be very helpful to adapt e.g. the title or similar seo relevant meta data.
To me it also seems a lot easier to provide those infos via fluid then via PageTitle API or other ways.

I would provide that small docu snippet if you want to but i got two questions:
1. where should i add that in the docs? (e.g. here: https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/8-Fluid/1-basic-concepts.html ? )
2. would it be smart to add that to the PageTitle and MetaTag Api as well? i was building on a plugin which provides the title for the page (so basically via its plugin content) - for that i checked the docs and could not properly figure out what to do – the HeaderAssets section was the best solution here for me so i would like to "crosslink" that https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/PageTitleApi/Index.html

The concrete feature i would like to mention:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Feature-79409-AutorenderAssetSectionsInFluidTemplateWithController.html

**Comment by DavidBruchmann** [comment]
Good catch!
At first it should be mentioned here: https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Section.html

In the first document you found might a good place to mention that the section-viewhelper changes the behavior based on the names `HeaderAssets` or `FooterAssets`.  
The second document you found is thematically just not fitting, as it's about an API which doesn't cover the issue.

**Comment by helsner** [comment]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/pull/39
