### ISSUE TITLE
Class does not exist: Tx_Extbase_Utility_Extension

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#62]
That class is used in https://docs.typo3.org/typo3cms/ExtbaseFluidBook/10-Outlook/2-Backend-modules.html

You have to use `\TYPO3\CMS\Extbase\Utility\ExtensionUtility` now.

**Comment by Ichag** [comment]
Looks like it's now fixed in the documentation. Time to close this issue?

**Comment by DanielSiepmann** [comment]
Thanks @Ichag.
It was fixed already, thanks for the notification.

**Comment by br4nnigan** [comment]
i installed the blog_example extention and got that error. Seems like the latest TYPO3 version is incompatible with the extention?

**Comment by cweiske** [comment]
This is the wrong place to file an issue for the blog_example.

**Comment by br4nnigan** [comment]
You got the hint, i'm out.
