### ISSUE TITLE
Part about Routing is missing

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#98]
For some people it's irritating that we don't provide information about how routes work in Extbase.

We should at least add a small paragraph or chapter about routing.
What's necessary, how does it work and how can someone adjust it.

We should provide the following:
- How to call a specific controller / action
- How to provide arguments

Hint at https://docs.typo3.org/typo3cms/ExtbaseFluidBook/10-Outlook/4-Property-mapping.html how mapping is done for actions.
Perhaps we should also mention that there are existing extensions to configure URLs.

Also we should explain how Extbase routing differs from normal frameworks, as Extbase is a Framework within TYPO3 CMS.
Perhaps we can mention page types and also https://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html#features would be a nice hint at `features.skipDefaultArguments`

**Comment by linawolf** [comment]
@DanielSiepmann can you provide a PR for this?

**Comment by DanielSiepmann** [comment]
Not sure if that's still relevant, due to the new routing introduced since 9.5.

It might still be useful. But I would say let's close this issue. It seems no one found it to important. Otherwise, there would have been more reactions or a PR.

**Comment by susannemoog** [comment]
I agree with Daniel and close this issue :)
